version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: always   
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    

  wordpress:
    depends_on:
      - db
    image: wordpress:6.3
    volumes:
      - ./wp-content:/var/www/wp-content/themes
      - ./wp-content:/var/www/html/wp-content/plugins
      - ./wp-content:/var/www/html/wp-content/uploads
    ports:
      - "7000:80"
    restart: always   
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress



 
